# Generated by Django 4.2.2 on 2023-07-07 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id_tecnica', models.AutoField(db_column='idTecnica', primary_key=True, serialize=False)),
                ('tecnica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.AutoField(db_column='id_obra', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('dimensiones', models.IntegerField()),
                ('destacada', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=400)),
                ('imagen', models.ImageField(upload_to='obras/')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artista')),
                ('id_tecnica', models.ForeignKey(db_column='idTecnica', on_delete=django.db.models.deletion.CASCADE, to='app.tecnica')),
            ],
        ),
    ]
