# Generated by Django 4.2.2 on 2023-06-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.BigIntegerField()),
                ('contraseña', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.BigIntegerField()),
                ('contraseña', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Duda',
            fields=[
                ('id_duda', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='dudas/')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('dimensiones', models.CharField(max_length=50)),
                ('destacada', models.BooleanField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='obras/')),
                ('administradores', models.ManyToManyField(to='app.administrador')),
                ('artistas', models.ManyToManyField(to='app.artista')),
                ('categorias', models.ManyToManyField(to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='TipoObra',
            fields=[
                ('id_tipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionCategoriaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obra')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionArtistaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artista')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obra')),
            ],
        ),
        migrations.CreateModel(
            name='RelacionArtistaDuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artista')),
                ('duda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.duda')),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoobra'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='obras',
            field=models.ManyToManyField(to='app.obra'),
        ),
    ]
