# Generated by Django 4.2.2 on 2023-06-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='obras',
        ),
        migrations.AlterField(
            model_name='artista',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='administradores',
            field=models.ManyToManyField(related_name='obras_administradas', to='app.administrador'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='artistas',
            field=models.ManyToManyField(related_name='obras_creadas', to='app.artista'),
        ),
        migrations.RemoveField(
            model_name='obra',
            name='categorias',
        ),
        migrations.AddField(
            model_name='obra',
            name='categorias',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
    ]
