# Generated by Django 4.2.2 on 2023-06-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_categoria_obras_alter_artista_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='id_obra',
            field=models.AutoField(db_column='idObra', primary_key=True, serialize=False),
        ),
    ]
